application: monxansh-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

# builtins:
# - datastore_admin: on
# - remote_api: on

# Cache static files
default_expiration: "14d"

handlers:
- url: /img
  static_dir: media
  expiration: "14d"

- url: /favicon\.ico
  static_files: media/favicon.ico
  expiration: "14d"
  upload: media/favicon\.ico

- url: /.*
  script: main.app
