application: monxansh
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: media
  
- url: /favicon\.ico
  static_files: media/favicon.ico
  upload: media/favicon\.ico


- url: .*
  script: main.py
