application: monxansh-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(favicon\.ico|robots\.txt|sitemap.xml)
  static_files: static/\1
  upload: static/.*

- url: /img
  static_dir: media
  expiration: "14d"

- url: /.*
  script: main.app
